version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: think_assistant_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: think_assistant_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: thinkuser
      POSTGRES_PASSWORD: thinkpass
      POSTGRES_DB: thinkdb
    restart: unless-stopped
